coverage:
  status:
    project:
      default:
        target: auto
        threshold: 5%
        base: auto 
        if_ci_failed: error #success, failure, error, ignore
        only_pulls: false
        flags: 
          - src
        paths: 
          - src/uv4
        removed_code_behavior: off #removals_only, fully_covered_patch, adjust_base",
